<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="ArtMagicWeb88.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <link href ="css/background.css" rel="stylesheet" />
   <div style="padding-top:40px;">
   </div>

    <div class="container"  >
        <h1 class="text-center">
        About Art Magic Web</h1>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px; padding: 0px; vertical-align: baseline; outline: 0px;  font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
            What started out as personal collection of works from Yogyakarta artists, built across the span of several years, formed the bulk of Artemis Art’s collection of works when we first began operations in 2010. Since then, much has changed. In early 2013 we moved to a different location within Publika, a place we called home until early 2021 when we made the decision to no longer operate a physical gallery for the time being.</p>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px; padding: 0px; vertical-align: baseline; outline: 0px;  font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
            In November 2021 Artemis Art turned 11, our decade anniversary coming at a time the world is going through great turmoil with the ongoing COVID-19 pandemic. Just as how the art world has had to make tremendous adjustments to how it operates, so has Artemis Art. Our activities are currently focused on our online presence, as well as exhibiting our artists through collaborations with galleries outside of Malaysia, and participating in art fairs when and where we are able to.</p>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px; padding: 0px; vertical-align: baseline; outline: 0px;  font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
            As a gallery our primary focus is on promoting young and emerging artists from the Southeast Asia region, whose diverse art-making modes and practices mirror the sheer diversity to be found in the region. Artemis Art is a firm believer in collaborations, and for the past several years have actively exhibited in neighboring countries through various collaborative models, thus far in China, Indonesia, Philippines, and Taiwan.</p>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px; padding: 0px; vertical-align: baseline; outline: 0px;  font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
            Although circumstance are such that it’s difficult to meet with us face to face, we are available pretty much 24/7.<span>&nbsp;</span><a href="../AboutUs" rel="noopener noreferrer" style="background: 0px 0px; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px; color: rgb(53, 126, 191); text-decoration: none; cursor: pointer;" target="_blank" title="Contact Us">Drop us a note</a><span>&nbsp;</span>via this website, or if you prefer, drop us<span>&nbsp;</span><a href="mailto:puahhj-wm19@student.tarc.edu.my" rel="noopener" style="background: 0px 0px; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px; color: rgb(53, 126, 191); text-decoration: none; cursor: pointer;" target="_blank">an email</a>. Alternatively, you can contact either one of the following:</p>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px; padding: 0px; vertical-align: baseline; outline: 0px; color: rgb(0, 0, 0); font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            <strong style="background: 0px 0px; color:white; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px;"><span>Peter Puah Hsien Jian&nbsp;</span></strong>&nbsp;at &nbsp;<strong style="background: 0px 0px; color:white; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px;">+60 19 321-<span>8340&nbsp;</span></strong>(e-mail:<span>&nbsp;<asp:HyperLink ID="email1" runat="server">peter@artmagicweb.com</asp:HyperLink>
            </span>), or<br />
            <strong style="background: 0px 0px; color:white; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px;"><span>Tee Zhe Kang&nbsp;</span></strong>at &nbsp;<strong style="background: 0px 0px; color:white; border: 0px; margin: 0px; padding: 0px; vertical-align: baseline; outline: 0px;">+60 12 373-2188&nbsp;</strong>(e-mail:<span>&nbsp;<asp:HyperLink ID="email2" runat="server">terence@artmagicweb.com</asp:HyperLink>
            </span>)</p>
        <p style="overflow-wrap: break-word; color:white;  border: 0px; margin: 10px 0px 0px; padding: 0px; vertical-align: baseline; outline: 0px;  font-weight: 400; font-family: Raleway, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            We look forward to hearing from you, and hopefully in the near future, be able to meet with you in person!</p>
        <p>
            &nbsp;</p>
    </div>
    
    <br />
    
    </asp:Content>
